spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*

ctrip:
  appid: 100003171
  
server:
  port: 7080
  
logging:
  file: /opt/logs/100003171/apollo-configservice.log
